-- MySQL Script generated by MySQL Workbench
-- Tue Mar 10 11:44:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ReproductorMusica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ReproductorMusica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ReproductorMusica` DEFAULT CHARACTER SET utf8 ;
USE `ReproductorMusica` ;

-- -----------------------------------------------------
-- Table `ReproductorMusica`.`Canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReproductorMusica`.`Canciones` (
  `idCancion` INT NOT NULL AUTO_INCREMENT,
  `titulo` TEXT(100) NOT NULL,
  `artista` TEXT(100) NOT NULL,
  `ruta` TEXT(100) NOT NULL,
  `duracion` INT NOT NULL,
  `favorito` TINYINT NOT NULL,
  PRIMARY KEY (`idCancion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
